### PR TITLE
Added ability to mark todo as done

### PR DESCRIPTION
**Pull request by sejlaali**
Ability to mark todo as completed should be implemented.
All completed todos have a strike-through and checked-square when marked complete.

### CODE REVIEW

**Comment by kingingcole** [comment]
Hello Sejlaali,
I just checked the preview deploy by Netlify (https://deploy-preview-11--todo-hook.netlify.com/) and the strike-through and checkboxcheckboxes are not working. You can check it out.
Also,  I have since made some changes to the same files you changed, hence the merge conflict. Pls update your local branch and make appropriate changes.
Please follow [this guide](https://help.github.com/en/articles/resolving-a-merge-conflict-on-github) to resolve conflicts. Tell me whenever and wherever you need help with.

**Comment by kingingcole** [comment]
I suggest you start with the strike-through and checkbox and I'll help with the merge conflicts

**Comment by sejlaali** [comment]
It works when I run it on my localhost but I'll look it over again and then re-commit. Thank you!

**Comment by sejlaali** [comment]
Please check preview deploy again when you get a chance. I committed my changes to App.js, which is where I declared the completeTodo() function. Let me know if the issue still persists.

**Comment by kingingcole** [comment]
Done @sejlaali. Nice additions, thanks a lor. 
One thing, ALWAYS make sure you have updated your own copy with the origina; repo before making a PR. I had already made some changes to some lines in the same files where you made your own changes.
>A merge conflict happens when two branches both modify the same region of a file and are subsequently merged. Git can't know which of the changes to keep, and thus needs human intervention to resolve the conflict.

**Comment by sejlaali** [comment]
I definitely will make sure to do so going forward. 
Thank you so much fo your help as this was my first contribution on Github!

**Pull request merged**
